CREATE TABLE Suppliers (
    SupplierID BIGINT PRIMARY KEY,
    SupplierName VARCHAR(100),
    ContactName VARCHAR(100),
    ContactEmail VARCHAR(100),
    Country VARCHAR(50)
)


INSERT INTO Suppliers (SupplierID, SupplierName, ContactName, ContactEmail, Country) VALUES
(1, 'Tech Supplies Inc.', 'John Doe', 'john@techsupplies.com', 'USA'),
(2, 'Furniture World', NULL, 'info@furnitureworld.com', 'Canada'),
(3, 'Office Essentials', 'Mary Johnson', 'mary@officeessentials.com', NULL),
(4, 'ElectroMart', 'James Wilson', NULL, 'UK'),
(5, 'GadgetZone', 'Emily Davis', 'emily@gadgetzone.com', 'Germany'),
(6, 'Home Comforts', 'Sophia Lee', 'sophia@homecomforts.com', 'USA'),
(7, 'AutoParts Co.', 'Michael Brown', 'michael@autoparts.com', 'Canada'),
(8, 'Best Electronics', 'Olivia Taylor', NULL, 'UK'),
(9, 'Kitchen World', 'Daniel Martinez', 'daniel@kitchenworld.com', 'Germany'),
(10, 'Office Needs', 'Emma Wilson', 'emma@officeneeds.com', 'USA'),
(11, 'Green Supplies', 'Liam Harris', NULL, 'Canada'),
(12, 'Global Imports', 'Noah Clark', 'noah@globalimports.com', 'UK'),
(13, 'Luxury Living', 'Ava Lewis', 'ava@luxuryliving.com', NULL),
(14, 'Furniture Experts', 'Ethan Hall', 'ethan@furnitureexperts.com', 'Germany'),
(15, 'Smart Home', 'Isabella Allen', 'isabella@smarthome.com', 'USA'),
(16, 'Fashion Forward', NULL, 'info@fashionforward.com', 'Canada'),
(17, 'Tech Gear', 'Lucas Scott', 'lucas@techgear.com', 'UK'),
(18, 'Pet Supplies Co.', 'Mia King', NULL, 'Germany'),
(19, 'Organic Farms', 'Elijah Wright', 'elijah@organicfarms.com', 'USA'),
(20, 'Health First', 'Charlotte Adams', 'charlotte@healthfirst.com', NULL),
(21, 'AutoPro', 'Benjamin Walker', 'benjamin@autopro.com', 'Canada'),
(22, 'Grocery Mart', 'Amelia Green', 'amelia@grocerymart.com', 'UK'),
(23, 'Music World', 'Henry Baker', NULL, 'Germany'),
(24, 'Home Builders', 'Sebastian Nelson', 'sebastian@homebuilders.com', 'USA'),
(25, 'Artistic Creations', 'Jack Carter', 'jack@artisticcreations.com', NULL),
(26, 'Sports Unlimited', 'Grace Mitchell', 'grace@sportsunlimited.com', 'Canada'),
(27, 'Smart Gadgets', 'William Perez', 'william@smartgadgets.com', 'UK'),
(28, 'Eco Solutions', 'James Roberts', NULL, 'Germany'),
(29, 'Luxury Watches', 'Natalie Phillips', 'natalie@luxurywatches.com', 'USA'),
(30, 'Food Delights', 'Daniel Sanchez', 'daniel@fooddelights.com', NULL),
(31, 'Beauty Essentials', 'Emily Torres', 'emily@beautyessentials.com', 'Canada'),
(32, 'Gaming Hub', 'Matthew Stewart', 'matthew@gaminghub.com', 'UK'),
(33, 'Book Haven', NULL, 'info@bookhaven.com', 'Germany'),
(34, 'Automotive Experts', 'Sophia Bennett', 'sophia@automotiveexperts.com', 'USA'),
(35, 'Outdoor Gear', 'Christopher Edwards', 'christopher@outdoorgear.com', 'Canada'),
(36, 'Tech Innovators', 'Aiden Morris', NULL, 'UK'),
(37, 'Kitchen Innovations', 'Harper Rogers', 'harper@kitcheninnovations.com', 'Germany'),
(38, 'Jewelry World', 'Evelyn Cook', 'evelyn@jewelryworld.com', 'USA'),
(39, 'Green Energy', 'Logan Morgan', 'logan@greenenergy.com', NULL),
(40, 'Luxury Cars', 'Madison Cooper', 'madison@luxurycars.com', 'Canada')
SELECT * FROM Suppliers
